cache_disabled_authenticated: true
cache_disabled_cookie_name: statamic_static_cache_skip
cache_disabled_user_roles: []
cache_disabled_user_groups: []
whitelisted_query_strings: []
cache_domain_enabled: false
warmup_collections: []
warmup_taxonomies: []
warmup_request_timeout: 0
debug_enabled: false
debug_string: <!-- Served by static cache -->
dynamic_csrf_enabled: false
dynamic_csrf_referer_base_url: ''
